name: Pipeline de test - Va échouer

on: [push]

jobs:
  test-fail:
    runs-on: ubuntu-latest
    steps:
      - name: Récupère le code
        uses: actions/checkout@v4

      - name: Vérifie que un fichier spécifique existe
        run: test -f "fichier-qui-nexiste-pas.txt"

      - name: Cette étape ne s'exécutera pas
        run: echo "Si tu vois ce message, l'étape précédente a réussi"

